name: sorcerers_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  web_socket_channel: ^3.0.0
  kt_dart: ^1.1.0
  sorcerers_core:
    path: ./packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
